### ISSUE TITLE
Use $(KOS_PORTS) instead of $(KOS_BASE)/../kos-ports

### ISSUE THREAD

**Issue by Tchan0** [psxdev/raylib4Dreamcast#1]
Hello,

Any possibility to change in Dreamcast_raylib.patch:
+PREFIX ?= $(KOS_BASE)/../kos-ports
into:
+PREFIX ?= $(KOS_PORTS)
?

When building eg for Naomi, one would have 2 different directories for /kos & kos-ports (eg /kosnaomi & /kos-portsnaomi, 
and would therefore change the default  $(KOS_PORTS) variable in environ.sh.

With the current hardcoding in Dreamcast_raylib.patch, the wrong folder is used.

(I wanted to quickly make a pull request from the online editor in github, but is says there is a mix of line endings, so the online editor has problems respecting that)

Thanks in advance && Thanks for making Raylib work with Kos !

T.

**Comment by psxdev** [comment]
Sure i will test it tomorrow and release new patch

**Comment by psxdev** [comment]
incorporated changes requested i close the issue by now
